import NewsFeed from '@modules/NewsFeed';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

const LANDING_PAGE_TITLE = 'Landing Page';

export default function Home() {
  const { status } = useSession();

  if (status === 'authenticated') {
    return (
      <>
        <Head>
          <title>{LANDING_PAGE_TITLE}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </>
    );
  }

  return <NewsFeed />;
}
